### ISSUE TITLE
environment issue

### ISSUE THREAD

**Issue by weiguangzhao** [renwuli/e3sym#1]
When I run pip install -r requirements.txt, the following happens. And my card is RTX4090
#############################################################################
Collecting easydict==1.10
  Using cached easydict-1.10.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... done
Collecting functorch==2.0.0
  Using cached functorch-2.0.0-py2.py3-none-any.whl (2.1 kB)
Collecting matplotlib==3.5.3
  Using cached matplotlib-3.5.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
Collecting numpy==1.21.6
  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting numba==0.56.4
  Using cached numba-0.56.4-cp37-cp37m-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
Collecting open3d==0.16.0
  Using cached open3d-0.16.0-cp37-cp37m-manylinux_2_27_x86_64.whl (422.4 MB)
Collecting opencv_python==4.6.0.66
  Using cached opencv_python-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.9 MB)
Collecting progressbar33==2.4
  Using cached progressbar33-2.4.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting pyvista==0.37.0
  Using cached pyvista-0.37.0-py3-none-any.whl (1.5 MB)
Collecting PyYAML==6.0
  Using cached PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
Collecting scikit_learn==1.0.2
  Downloading scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.8/24.8 MB 14.6 MB/s eta 0:00:00
Collecting torch==1.12.1
  Downloading torch-1.12.1-cp37-cp37m-manylinux1_x86_64.whl (776.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 776.3/776.3 MB 2.7 MB/s eta 0:00:00
Collecting tqdm==4.64.1
  Downloading tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 30.4 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of easydict to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 2) and torch==1.12.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==1.12.1
    functorch 2.0.0 depends on torch<2.1 and >=2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
WARNING: There was an error checking the latest version of pip.

**Comment by renwuli** [comment]
sorry for the issue, the `functorch` maybe unnecessary, you can delete this line in requirements.txt and try again.
