### ISSUE TITLE
How to get the confidence score of each plane?

### ISSUE THREAD

**Issue by weiguangzhao** [renwuli/e3sym#2]
Hi, thanks for your great work.  I found that some point clouds have 2-3 symmetry planes. How to output the confidence of these planes? Your code only outputs plane and batch information.  I want to retain only one plane for each object.
![image](https://github.com/renwuli/e3sym/assets/22412975/cdd5523a-b9d4-4780-81d4-869d49100963)
![image](https://github.com/renwuli/e3sym/assets/22412975/9683feec-a648-404a-b0f9-f09e4fc14746)

**Comment by renwuli** [comment]
please refer to Sec 3.3 in the paper "Planar Symmetry Inference", there is a simple and easy-to-implement strategy to filter out wrong or imperfect symmetries, for a specific model, you might need to tune the hyper-parameters to get best accuracy.
